### ISSUE TITLE
PLEASE HELP ME BRO

### ISSUE THREAD

**Issue by fcoremedi** [kotleni/csgo-run#1]
Hey bro! I have OS X Ventura
and I'm trying to launch the Wallhack but I can't, can you help me pls bro!! I really excited to try to used the Wallhack but i can't do it myself, pls!!!

**Comment by kotleni** [comment]
What problem are you facing? Can you clarify?

**Comment by FearLessOne7** [comment]
Hey, for some reason when I install, the csgo_osx64 file isnt there

**Comment by FearLessOne7** [comment]
it says:
clang: error: no such file or directory: 'csgo_run.c'
clang: error: no input files
after I try to run the gcc -pthread -o csgo_osx64 csgo_run.c command

**Comment by FearLessOne7** [comment]
nvm, got it working! thanks!

**Comment by fcoremedi** [comment]
how you fixed that bro!?
can you help me pls I want to launch the glow D:

**Comment by FearLessOne7** [comment]
I ended up chaging the file name that I received from csgo_run to csgo_osx64 (not sure if it makes a difference)

**Comment by fcoremedi** [comment]
bro give me your discord pls!! I really excited to try this glow hack pls bro!!

**Comment by FearLessOne7** [comment]
Whats your discord?

**Comment by fcoremedi** [comment]
fcoremedi#4121
