### ISSUE TITLE
Did not understand the procedures in readme.md

### ISSUE THREAD

**Issue by Tediscool2** [kotleni/csgo-run#2]
These screenshots are from the youtube video provided, how are those there?
![Screenshot 2022-12-26 at 7 31 27 PM](https://user-images.githubusercontent.com/107658874/209544305-6c5a763e-edeb-40ca-8dd4-3583b068c4c9.png)
![Screenshot 2022-12-26 at 7 31 59 PM](https://user-images.githubusercontent.com/107658874/209544348-fd11e587-950b-4e80-986d-17066af9f807.png)

**Comment by kotleni** [comment]
@Tediscool2 I updated docs in repository, you can check it in new readme.
