### ISSUE TITLE
Cs:GO isnt launching after replacing csgo_osx64

### ISSUE THREAD

**Issue by PHILKAULTRA** [kotleni/csgo-run#4]
Cs:GO isnt launching after replacing csgo_osx64, even without injecting or something

**Comment by PHILKAULTRA** [comment]
/Users/myname/Library/Application\ Support/Steam/steamapps/common/Counter-Strike\ Global\ Offensive/csgo_osx64 ; exit;
Failed to load the launcher (dlopen(bin/osx64/launcher.dylib, 0x0002): tried: 'bin/osx64/launcher.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSbin/osx64/launcher.dylib' (no such file), '/usr/lib/bin/osx64/launcher.dylib' (no such file, not in dyld cache), 'bin/osx64/launcher.dylib' (no such file))

Here is an error in terminal

**Comment by PHILKAULTRA** [comment]
No, thats not an error, sorry

**Comment by kotleni** [comment]
What is you CPU? How you builded it?
